### ISSUE TITLE
Resolution of test JAR from local Ivy repo doesn't work

### ISSUE THREAD

**Issue by durban** [alexarchambault/coursier#318]
Example project: https://github.com/durban/coursier-example

Steps to reproduce:
1. in project "a", run `publishLocal`
2. in project "b", run `test:compile`

If coursier is enabled as a global sbt plugin (version `1.0.0-M12-1`), step 2. fails with a compile error (`object TestA is not a member of package com.example.a`). Otherwise it succeeds, as expected.

Note, that it doesn't seem to matter whether coursier is enabled when running `publishLocal`, it only makes a difference when running the `test:compile`.

**Comment by alexarchambault** [comment]
That should be fixed in 1.0.0-M13, thanks to https://github.com/alexarchambault/coursier/commit/22c7340f6fe4b8975c88b2091617176b955758c5. Can you try that again?

**Comment by durban** [comment]
I tried it with 1.0.0-M13, and I get the same error.

**Comment by durban** [comment]
I retested with 1.0.0-**M14**, and the behavior is still the same.

**Comment by avdv** [comment]
I ran into the same issue. I'm trying to depend on `test->test` artifacts in a remote ivy repository and the classes are just not found when compiling.

I'm using 1.0.0-M14 too.
